# permissions for end users to edit pullstates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pullstate-editor-role
rules:
- apiGroups:
  - hitachi.hitachienergy.com
  resources:
  - pullstates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hitachi.hitachienergy.com
  resources:
  - pullstates/status
  verbs:
  - get
